"""
NutriPath — clinical rule tables → seed migration.

Reads `tools/rules/nutrient_limits.py` (the canonical, human-editable rule source:
`NUTRIENT_LIMITS` + `FOOD_EXCLUSIONS`) and writes `supabase/migrations/0003_seed_nutrient_limits.sql`.

The DB is the RUNTIME source of truth — the edge function reads `nutrient_limits` /
`food_exclusions` generically. Adding a future disease/limit = add rows to the Python
file (or INSERT SQL directly), regenerate, re-push. No application code changes.

Condition slugs are resolved via subselect so 0003 applies in any order after 0002.
Idempotent: `ON CONFLICT ... DO UPDATE`.

Usage:
    python tools/gen_rules.py
"""

from __future__ import annotations

import argparse
import importlib.util
from pathlib import Path
from typing import Any

ROOT = Path(__file__).resolve().parent.parent
DEFAULT_RULES = ROOT / "tools" / "rules" / "nutrient_limits.py"
DEFAULT_OUTPUT = ROOT / "supabase" / "migrations" / "0003_seed_nutrient_limits.sql"


def load_rules(path: Path) -> dict[str, Any]:
    spec = importlib.util.spec_from_file_location("nutrient_limits", path)
    if spec is None or spec.loader is None:
        raise SystemExit(f"cannot load rules from {path}")
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return {
        "nutrient_limits": getattr(module, "NUTRIENT_LIMITS", {}),
        "food_exclusions": getattr(module, "FOOD_EXCLUSIONS", {}),
    }


def sql_literal(value: Any) -> str:
    if value is None:
        return "NULL"
    if isinstance(value, bool):
        return "TRUE" if value else "FALSE"
    if isinstance(value, (int, float)):
        return repr(value)
    return "'" + str(value).replace("'", "''") + "'"


def generate_nutrient_limits(rules: dict[str, Any]) -> list[str]:
    stmts: list[str] = []
    for condition_slug, payload in rules.items():
        source = payload.get("source")
        for nutrient, limit in payload.items():
            if nutrient == "source":
                continue
            max_val = limit.get("max")
            min_val = limit.get("min")
            unit = limit.get("unit")
            note = limit.get("note")
            if max_val is None and min_val is None:
                # flag-style rule (e.g. goitrogen_flag) — nothing to enforce yet
                continue
            stmts.append(
                "INSERT INTO nutrient_limits "
                "(condition_id, nutrient, max_value, min_value, unit, note, source) VALUES\n"
                f"  ((SELECT id FROM conditions WHERE slug = {sql_literal(condition_slug)}), "
                f"{sql_literal(nutrient)}, {sql_literal(max_val)}, {sql_literal(min_val)}, "
                f"{sql_literal(unit)}, {sql_literal(note)}, {sql_literal(source)})\n"
                "ON CONFLICT (condition_id, nutrient) DO UPDATE SET\n"
                "  max_value = EXCLUDED.max_value,\n"
                "  min_value = EXCLUDED.min_value,\n"
                "  unit = EXCLUDED.unit,\n"
                "  note = EXCLUDED.note,\n"
                "  source = EXCLUDED.source;"
            )
    return stmts


def generate_food_exclusions(rules: dict[str, Any]) -> list[str]:
    stmts: list[str] = []
    for condition_slug, payload in rules.items():
        source = payload.get("source")
        for tag in payload.get("excluded_tags", []):
            stmts.append(
                "INSERT INTO food_exclusions "
                "(condition_id, excluded_tag, source) VALUES\n"
                f"  ((SELECT id FROM conditions WHERE slug = {sql_literal(condition_slug)}), "
                f"{sql_literal(tag)}, {sql_literal(source)})\n"
                "ON CONFLICT (condition_id, excluded_tag) DO UPDATE SET\n"
                "  source = EXCLUDED.source;"
            )
    return stmts


def generate_sql(rules: dict[str, Any]) -> str:
    limit_stmts = generate_nutrient_limits(rules["nutrient_limits"])
    exclusion_stmts = generate_food_exclusions(rules["food_exclusions"])
    return (
        "-- 0003_seed_nutrient_limits.sql\n"
        "-- GENERATED BY tools/gen_rules.py — DO NOT EDIT BY HAND.\n"
        "-- Source: tools/rules/nutrient_limits.py (clinical rule tables)\n"
        "-- Regenerate:  python tools/gen_rules.py\n"
        "-- The DB is the runtime source of truth; the edge function reads these generically.\n"
        "\n"
        + ("-- nutrient_limits (threshold-based rules)\n\n" + "\n\n".join(limit_stmts) + "\n"
           if limit_stmts else "-- no nutrient limits to seed\n")
        + "\n"
        + ("-- food_exclusions (tag-based excludes)\n\n" + "\n\n".join(exclusion_stmts) + "\n"
           if exclusion_stmts else "-- no food exclusions to seed\n")
    )


def main() -> None:
    parser = argparse.ArgumentParser(description="Generate 0003_seed_nutrient_limits.sql from the rule tables")
    parser.add_argument("--rules", type=Path, default=DEFAULT_RULES)
    parser.add_argument("--output", type=Path, default=DEFAULT_OUTPUT)
    args = parser.parse_args()

    if not args.rules.exists():
        raise SystemExit(f"rules not found: {args.rules}")

    rules = load_rules(args.rules)
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(generate_sql(rules), encoding="utf-8")

    n_conditions = len(rules["nutrient_limits"])
    n_exclusions = len(rules["food_exclusions"])
    print(
        f"wrote {args.output} — "
        f"{n_conditions} conditions, "
        f"{sum(len(v) - 1 for v in rules['nutrient_limits'].values())} nutrient limits, "
        f"{sum(len(v.get('excluded_tags', [])) for v in rules['food_exclusions'].values())} exclusion tags"
    )


if __name__ == "__main__":
    main()
