-- 0003_seed_nutrient_limits.sql
-- GENERATED BY tools/gen_rules.py — DO NOT EDIT BY HAND.
-- Source: tools/rules/nutrient_limits.py (clinical rule tables)
-- Regenerate:  python tools/gen_rules.py
-- The DB is the runtime source of truth; the edge function reads these generically.

-- nutrient_limits (threshold-based rules)

INSERT INTO nutrient_limits (condition_id, nutrient, max_value, min_value, unit, note, source) VALUES
  ((SELECT id FROM conditions WHERE slug = 'type2_diabetes'), 'sugar_g', 25, NULL, 'g', 'Added sugar limit - ADA', 'ADA Standards of Care in Diabetes')
ON CONFLICT (condition_id, nutrient) DO UPDATE SET
  max_value = EXCLUDED.max_value,
  min_value = EXCLUDED.min_value,
  unit = EXCLUDED.unit,
  note = EXCLUDED.note,
  source = EXCLUDED.source;

INSERT INTO nutrient_limits (condition_id, nutrient, max_value, min_value, unit, note, source) VALUES
  ((SELECT id FROM conditions WHERE slug = 'type2_diabetes'), 'carbs_g', 200, NULL, 'g', 'Total carb budget, adjust per calorie needs - ADA', 'ADA Standards of Care in Diabetes')
ON CONFLICT (condition_id, nutrient) DO UPDATE SET
  max_value = EXCLUDED.max_value,
  min_value = EXCLUDED.min_value,
  unit = EXCLUDED.unit,
  note = EXCLUDED.note,
  source = EXCLUDED.source;

INSERT INTO nutrient_limits (condition_id, nutrient, max_value, min_value, unit, note, source) VALUES
  ((SELECT id FROM conditions WHERE slug = 'type2_diabetes'), 'fiber_g', NULL, 25, 'g', 'Encourage - slows glucose absorption', 'ADA Standards of Care in Diabetes')
ON CONFLICT (condition_id, nutrient) DO UPDATE SET
  max_value = EXCLUDED.max_value,
  min_value = EXCLUDED.min_value,
  unit = EXCLUDED.unit,
  note = EXCLUDED.note,
  source = EXCLUDED.source;

INSERT INTO nutrient_limits (condition_id, nutrient, max_value, min_value, unit, note, source) VALUES
  ((SELECT id FROM conditions WHERE slug = 'hypertension'), 'sodium_mg', 1500, NULL, 'mg', 'DASH diet target - AHA', 'AHA / DASH Diet Guidelines')
ON CONFLICT (condition_id, nutrient) DO UPDATE SET
  max_value = EXCLUDED.max_value,
  min_value = EXCLUDED.min_value,
  unit = EXCLUDED.unit,
  note = EXCLUDED.note,
  source = EXCLUDED.source;

INSERT INTO nutrient_limits (condition_id, nutrient, max_value, min_value, unit, note, source) VALUES
  ((SELECT id FROM conditions WHERE slug = 'hypertension'), 'sat_fat_g', 13, NULL, 'g', 'AHA saturated fat limit (~6% of 2000kcal diet)', 'AHA / DASH Diet Guidelines')
ON CONFLICT (condition_id, nutrient) DO UPDATE SET
  max_value = EXCLUDED.max_value,
  min_value = EXCLUDED.min_value,
  unit = EXCLUDED.unit,
  note = EXCLUDED.note,
  source = EXCLUDED.source;

INSERT INTO nutrient_limits (condition_id, nutrient, max_value, min_value, unit, note, source) VALUES
  ((SELECT id FROM conditions WHERE slug = 'hypertension'), 'potassium_mg', NULL, 3500, 'mg', 'Encourage - AHA', 'AHA / DASH Diet Guidelines')
ON CONFLICT (condition_id, nutrient) DO UPDATE SET
  max_value = EXCLUDED.max_value,
  min_value = EXCLUDED.min_value,
  unit = EXCLUDED.unit,
  note = EXCLUDED.note,
  source = EXCLUDED.source;

INSERT INTO nutrient_limits (condition_id, nutrient, max_value, min_value, unit, note, source) VALUES
  ((SELECT id FROM conditions WHERE slug = 'dyslipidemia'), 'sat_fat_g', 13, NULL, 'g', 'AHA lipid guideline', 'AHA Cholesterol Guidelines')
ON CONFLICT (condition_id, nutrient) DO UPDATE SET
  max_value = EXCLUDED.max_value,
  min_value = EXCLUDED.min_value,
  unit = EXCLUDED.unit,
  note = EXCLUDED.note,
  source = EXCLUDED.source;

INSERT INTO nutrient_limits (condition_id, nutrient, max_value, min_value, unit, note, source) VALUES
  ((SELECT id FROM conditions WHERE slug = 'dyslipidemia'), 'trans_fat_g', 0, NULL, 'g', 'AHA - avoid entirely', 'AHA Cholesterol Guidelines')
ON CONFLICT (condition_id, nutrient) DO UPDATE SET
  max_value = EXCLUDED.max_value,
  min_value = EXCLUDED.min_value,
  unit = EXCLUDED.unit,
  note = EXCLUDED.note,
  source = EXCLUDED.source;

INSERT INTO nutrient_limits (condition_id, nutrient, max_value, min_value, unit, note, source) VALUES
  ((SELECT id FROM conditions WHERE slug = 'dyslipidemia'), 'fiber_g', NULL, 25, 'g', 'Encourage - soluble fiber lowers LDL', 'AHA Cholesterol Guidelines')
ON CONFLICT (condition_id, nutrient) DO UPDATE SET
  max_value = EXCLUDED.max_value,
  min_value = EXCLUDED.min_value,
  unit = EXCLUDED.unit,
  note = EXCLUDED.note,
  source = EXCLUDED.source;

INSERT INTO nutrient_limits (condition_id, nutrient, max_value, min_value, unit, note, source) VALUES
  ((SELECT id FROM conditions WHERE slug = 'ckd'), 'potassium_mg', 2000, NULL, 'mg', 'KDIGO - varies by CKD stage, this is moderate-stage default', 'KDIGO Clinical Practice Guideline for Nutrition in CKD')
ON CONFLICT (condition_id, nutrient) DO UPDATE SET
  max_value = EXCLUDED.max_value,
  min_value = EXCLUDED.min_value,
  unit = EXCLUDED.unit,
  note = EXCLUDED.note,
  source = EXCLUDED.source;

INSERT INTO nutrient_limits (condition_id, nutrient, max_value, min_value, unit, note, source) VALUES
  ((SELECT id FROM conditions WHERE slug = 'ckd'), 'phosphorus_mg', 800, NULL, 'mg', 'KDIGO', 'KDIGO Clinical Practice Guideline for Nutrition in CKD')
ON CONFLICT (condition_id, nutrient) DO UPDATE SET
  max_value = EXCLUDED.max_value,
  min_value = EXCLUDED.min_value,
  unit = EXCLUDED.unit,
  note = EXCLUDED.note,
  source = EXCLUDED.source;

INSERT INTO nutrient_limits (condition_id, nutrient, max_value, min_value, unit, note, source) VALUES
  ((SELECT id FROM conditions WHERE slug = 'ckd'), 'sodium_mg', 2000, NULL, 'mg', 'KDIGO', 'KDIGO Clinical Practice Guideline for Nutrition in CKD')
ON CONFLICT (condition_id, nutrient) DO UPDATE SET
  max_value = EXCLUDED.max_value,
  min_value = EXCLUDED.min_value,
  unit = EXCLUDED.unit,
  note = EXCLUDED.note,
  source = EXCLUDED.source;

INSERT INTO nutrient_limits (condition_id, nutrient, max_value, min_value, unit, note, source) VALUES
  ((SELECT id FROM conditions WHERE slug = 'ckd'), 'protein_g', 60, NULL, 'g', 'KDIGO - non-dialysis default, ~0.8g/kg/day for 75kg adult', 'KDIGO Clinical Practice Guideline for Nutrition in CKD')
ON CONFLICT (condition_id, nutrient) DO UPDATE SET
  max_value = EXCLUDED.max_value,
  min_value = EXCLUDED.min_value,
  unit = EXCLUDED.unit,
  note = EXCLUDED.note,
  source = EXCLUDED.source;

INSERT INTO nutrient_limits (condition_id, nutrient, max_value, min_value, unit, note, source) VALUES
  ((SELECT id FROM conditions WHERE slug = 'gout'), 'purine_mg', 400, NULL, 'mg', 'ACR - limit high-purine foods (organ meat, certain seafood)', 'ACR Guideline for Management of Gout')
ON CONFLICT (condition_id, nutrient) DO UPDATE SET
  max_value = EXCLUDED.max_value,
  min_value = EXCLUDED.min_value,
  unit = EXCLUDED.unit,
  note = EXCLUDED.note,
  source = EXCLUDED.source;

INSERT INTO nutrient_limits (condition_id, nutrient, max_value, min_value, unit, note, source) VALUES
  ((SELECT id FROM conditions WHERE slug = 'gout'), 'sugar_g', 25, NULL, 'g', 'ACR - limit fructose, linked to uric acid', 'ACR Guideline for Management of Gout')
ON CONFLICT (condition_id, nutrient) DO UPDATE SET
  max_value = EXCLUDED.max_value,
  min_value = EXCLUDED.min_value,
  unit = EXCLUDED.unit,
  note = EXCLUDED.note,
  source = EXCLUDED.source;

INSERT INTO nutrient_limits (condition_id, nutrient, max_value, min_value, unit, note, source) VALUES
  ((SELECT id FROM conditions WHERE slug = 'arthritis'), 'omega3_g', NULL, 2, 'g', 'Encourage - anti-inflammatory, ACR dietary guidance', 'ACR Dietary Recommendations for Inflammatory Arthritis')
ON CONFLICT (condition_id, nutrient) DO UPDATE SET
  max_value = EXCLUDED.max_value,
  min_value = EXCLUDED.min_value,
  unit = EXCLUDED.unit,
  note = EXCLUDED.note,
  source = EXCLUDED.source;

INSERT INTO nutrient_limits (condition_id, nutrient, max_value, min_value, unit, note, source) VALUES
  ((SELECT id FROM conditions WHERE slug = 'arthritis'), 'sat_fat_g', 15, NULL, 'g', 'Limit pro-inflammatory fats', 'ACR Dietary Recommendations for Inflammatory Arthritis')
ON CONFLICT (condition_id, nutrient) DO UPDATE SET
  max_value = EXCLUDED.max_value,
  min_value = EXCLUDED.min_value,
  unit = EXCLUDED.unit,
  note = EXCLUDED.note,
  source = EXCLUDED.source;

INSERT INTO nutrient_limits (condition_id, nutrient, max_value, min_value, unit, note, source) VALUES
  ((SELECT id FROM conditions WHERE slug = 'hypothyroidism'), 'iodine_mcg', 500, NULL, 'mcg', 'ATA - avoid excess, esp. if on levothyroxine', 'American Thyroid Association Guidelines')
ON CONFLICT (condition_id, nutrient) DO UPDATE SET
  max_value = EXCLUDED.max_value,
  min_value = EXCLUDED.min_value,
  unit = EXCLUDED.unit,
  note = EXCLUDED.note,
  source = EXCLUDED.source;

INSERT INTO nutrient_limits (condition_id, nutrient, max_value, min_value, unit, note, source) VALUES
  ((SELECT id FROM conditions WHERE slug = 'nafld'), 'sugar_g', 25, NULL, 'g', 'AASLD - limit fructose/added sugar', 'AASLD Practice Guidance for NAFLD')
ON CONFLICT (condition_id, nutrient) DO UPDATE SET
  max_value = EXCLUDED.max_value,
  min_value = EXCLUDED.min_value,
  unit = EXCLUDED.unit,
  note = EXCLUDED.note,
  source = EXCLUDED.source;

INSERT INTO nutrient_limits (condition_id, nutrient, max_value, min_value, unit, note, source) VALUES
  ((SELECT id FROM conditions WHERE slug = 'nafld'), 'sat_fat_g', 13, NULL, 'g', 'AASLD', 'AASLD Practice Guidance for NAFLD')
ON CONFLICT (condition_id, nutrient) DO UPDATE SET
  max_value = EXCLUDED.max_value,
  min_value = EXCLUDED.min_value,
  unit = EXCLUDED.unit,
  note = EXCLUDED.note,
  source = EXCLUDED.source;

INSERT INTO nutrient_limits (condition_id, nutrient, max_value, min_value, unit, note, source) VALUES
  ((SELECT id FROM conditions WHERE slug = 'obesity'), 'fiber_g', NULL, 25, 'g', 'Encourage - satiety', 'General calorie-density + satiety guidance')
ON CONFLICT (condition_id, nutrient) DO UPDATE SET
  max_value = EXCLUDED.max_value,
  min_value = EXCLUDED.min_value,
  unit = EXCLUDED.unit,
  note = EXCLUDED.note,
  source = EXCLUDED.source;

-- food_exclusions (tag-based excludes)

INSERT INTO food_exclusions (condition_id, excluded_tag, source) VALUES
  ((SELECT id FROM conditions WHERE slug = 'celiac'), 'contains_gluten', 'Celiac Disease Foundation / gluten-free dietary standard')
ON CONFLICT (condition_id, excluded_tag) DO UPDATE SET
  source = EXCLUDED.source;

INSERT INTO food_exclusions (condition_id, excluded_tag, source) VALUES
  ((SELECT id FROM conditions WHERE slug = 'celiac'), 'wheat', 'Celiac Disease Foundation / gluten-free dietary standard')
ON CONFLICT (condition_id, excluded_tag) DO UPDATE SET
  source = EXCLUDED.source;

INSERT INTO food_exclusions (condition_id, excluded_tag, source) VALUES
  ((SELECT id FROM conditions WHERE slug = 'celiac'), 'barley', 'Celiac Disease Foundation / gluten-free dietary standard')
ON CONFLICT (condition_id, excluded_tag) DO UPDATE SET
  source = EXCLUDED.source;

INSERT INTO food_exclusions (condition_id, excluded_tag, source) VALUES
  ((SELECT id FROM conditions WHERE slug = 'celiac'), 'rye', 'Celiac Disease Foundation / gluten-free dietary standard')
ON CONFLICT (condition_id, excluded_tag) DO UPDATE SET
  source = EXCLUDED.source;
